config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  namespace :api do
    resources :favorites, only: [:create, :destroy]
  end

  resources :properties, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :property

  # Optional: Validations to ensure arrays have values if needed
  validates :languages_spoken, :accessibility, :internet_access, 
            :cleanliness_and_safety, :food_and_dinning, 
            :access, :services_and_conveniences, :getting_around, 
            presence: true, allow_blank: true


  def highlighted_facilities
    KeywordExtractor.extract_highlighted_facilities(self)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
    
    attribute :additional_attributes, :jsonb, default: {}
    validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :address_line_1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :country, presence: true
	validates :additional_attributes, presence: true, if: -> { additional_attributes.is_a?(Hash) }
	monetize :price_cents, allow_nil: true

	has_many_attached :images 
	has_many :reviews, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
	has_many :reservations, dependent: :destroy
    has_many :reserved_users, through: :reservations, source: :property, dependent: :destroy
    has_one :facility, dependent: :destroy

	def update_average_final_rating
		avg_rating = (self.reviews.average(:final_rating)).to_f
		update_columns(avg_final_rating: avg_rating)
	end

	def favorite_by?(user=nil)
		return if user.nil?
		favorite_users.include?(user)
	end

	def available_dates
	  current_res = reservations.ongoing_reservations.first
	  next_res = reservations.upcoming_reservations.first

	  from_date = current_res&.check_out_date || Date.tomorrow
	  to_date = next_res&.check_in_date || (Date.today + 20.days)

	  "#{from_date.strftime('%d %b')} - #{to_date.strftime('%d %b')}"
	end

	def additional_attributes_with_check_in_check_out
		self.additional_attributes["check_in_check_out"]
	end

	def additional_attributes_with_extras
		self.additional_attributes["extras"]
	end

	def additional_attributes_with_the_property
		self.additional_attributes["the_property"]
	end

	def additional_attributes_with_getting_around
		self.additional_attributes["getting_around"]
	end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :check_in_date, presence: true
  validates :check_out_date, presence: true, comparison: { greater_than: :check_in_date }

  scope :upcoming_reservations, -> { where("check_in_date > ?", Date.today).order(:check_in_date) }
  scope :ongoing_reservations, -> { where("check_out_date >= ?", Date.today).where("check_in_date <= ?", Date.today).order(:check_out_date) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :property, counter_cache: true

  validates :content, presence: true
  validates :location_rating, numericality: { only_numeric: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :service_rating, numericality: { only_numeric: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 11 }
  validates :room_comfort_quality_rating, numericality: { only_numeric: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 11 }
  validates :cleanliness_rating, numericality: { only_numeric: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 11 }
  validates :facilities_rating, numericality: { only_numeric: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 11 }
  validates :value_for_money_rating, numericality: { only_numeric: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 11 }

  after_commit :update_final_rating, on:[:create,:update]

  def update_final_rating
    total_ratings_count = self.location_rating + 
    self.service_rating + 
    self.room_comfort_quality_rating + 
    self.cleanliness_rating + 
    self.facilities_rating + 
    self.value_for_money_rating

    self.final_rating = ((total_ratings_count / 6.0).to_f.round(2))
    update_column(:final_rating, self.final_rating)
    property.update_average_final_rating
  end

  def reviews_count
    self.reviews.count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :favorite_properties, through: :favorites, source: :property, dependent: :destroy

  has_many :reservations, dependent: :destroy
  has_many :reserved_properties, through: :reservations, source: :property, dependent: :destroy
end

app/controllers/api/favorites_controller.rb
module Api
	class FavoritesController < ApplicationController
		protect_from_forgery with: :null_session

		def create
			@favorite = Favorite.create!(favorite_params)
			respond_to do |format|
				format.json { render json: @favorite.to_json, status: :ok, message: 'Property added to Favorites' }
			end
		end

		def destroy
			@favorite = Favorite.find_by(id: params[:id])
			if @favorite
				@favorite.destroy!
				respond_to do |format|
				  format.json { render json: { success: 'Property removed from Favorites' }, status: :no_content} # 204 No Content is appropriate for deletions
				end
			else
				respond_to do |format|
				  format.json { render json: { error: 'Failed to remove Property from Favorites' }, status: :not_found }
				end
			end
		end

		private

		def favorite_params
			params.permit(:user_id, :property_id)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	def show
		@properties = Property.find params[:id]
		@facilities = @properties.facility
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def show_svg(path)
	  File.open("app/assets/images/#{path}", "rb") do |file|
	    raw file.read
	  end
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def rating_progress_bar(label, value)
    percentage = (value.to_f * 10).round # Convert rating to percentage (e.g., 7.5 -> 75%)

    content_tag(:div, class: "mb-2") do
      concat(content_tag(:div, class: "flex justify-between font-medium") do
        concat content_tag(:span, label)
        concat content_tag(:span, value.round(1).to_s)
      end)

      concat(content_tag(:div, class: "w-full bg-gray-200 rounded h-2 mb-2") do
        content_tag(:div, "", class: "bg-green-500 h-2", style: "width: #{percentage}%;")
      end)
    end
  end

  def final_rating_label(final_rating)
    case final_rating.to_f
    when 9..10
      "#{final_rating.to_s} Exceptional"
    when 8...9
      "#{final_rating.to_s} Excellent"
    when 7...8
      "#{final_rating.to_s} Very Good"
    when 6...7
      "#{final_rating.to_s} Good"
    else
      "#{final_rating.to_s} Below Expectation"
    end
  end

  def display_property_review_averages(all_reviews)
    reviews = all_reviews

    # Calculate average for each category
    ratings = {
      "Location" => reviews.average(:location_rating) || 0,
      "Cleanliness" => reviews.average(:cleanliness_rating) || 0,
      "Service" => reviews.average(:service_rating) || 0,
      "Value for Money" => reviews.average(:value_for_money_rating) || 0,
      "Room Comfort Quality" => reviews.average(:room_comfort_quality_rating) || 0,
      "Facilities" => reviews.average(:facilities_rating) || 0
    }

    content_tag(:div) do
      # Generate individual ratings with progress bars
      concat(ratings.map { |label, value| rating_progress_bar(label, value) }.join.html_safe)
    end
  end
end

app/views/home/index.html.erb
<% @properties.each_with_index do |property| %>
  <%= link_to property_path(property) do %>
    <div class="container mx-auto p-4 md:p-10 antialiased">
      <div class="flex flex-wrap lg:flex-nowrap shadow-lg mx-auto max-w-10xl cursor-pointer transform duration-500 hover:-translate-y-1">
        <div class="w-full xl:w-1/4 lg:w-1/2 ">
          <div class="swiper">
            <div class="absolute z-10 right-0 top-0 m-4 <%= property.favorite_by?(current_user) ? 'fill-orange-600' : 'fill-yellow-100' %>">
              <svg class="block h-6 w-6" style="overflow: visible;" 
              data-controller="favorite" 
              data-action="click->favorite#update_favorite_list" 
              data-status="<%= property.favorite_by?(current_user) %>"  
              data-user-logged-in="<%= user_signed_in? %>"
              data-property-id="<%= property.id %>"
              data-user-id="<%= current_user&.id %>"
              data-favorite-id="<%= property.favorite_by?(current_user) ? property.favorites.find_by(user_id: current_user).id : nil %>"
              height="24px" width="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
              </svg>
            </div>
            <div class="swiper-wrapper">
              <% property.images.each do |image| %>
                  <%= image_tag image, class: "swiper-slide w-full object-cover rounded-lg aspect-[4/3]" %>
              <% end %>
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
          </div>
        </div>
        <div class="flex-grow flex flex-col justify-evenly" style="width: 300px;">
          <div class="p-4 pb-2">
            <h1 class="text-2xl font-semibold text-gray-600 mt-4">
              <%= property.name %>
            </h1>
            <h2 class="text-gray-600">
              <%= "#{property.city} | #{property.state} | #{property.country}" %>
            </h2>
            <p class="text-l text-gray-400 mt-2 leading-relaxed">
              <%= property.description %>
            </p>
          </div>

          <div class="bg-blue-50 p-5">
            <div class="flex justify-between ai-style-change-1">
              <div class="flex items-center">
                <% full_stars = (property.avg_final_rating / 2).floor %>
                <% half_star = (property.avg_final_rating % 2) >= 1 %>
                <% empty_stars = 5 - (full_stars + (half_star ? 1 : 0)) %>

                <% full_stars.times do %>
                  <svg class="w-5 h-5 text-yellow-300 me-1" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                  </svg>
                <% end %>

                <% if half_star %>
                  <svg class="w-5 h-5 text-yellow-300 me-1" fill="currentColor" viewBox="0 0 22 20">
                    <defs>
                      <linearGradient id="half-star">
                        <stop offset="50%" stop-color="currentColor"/>
                        <stop offset="50%" stop-color="gray"/>
                      </linearGradient>
                    </defs>
                    <path fill="url(#half-star)" d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                  </svg>
                <% end %>

                <% empty_stars.times do %>
                  <svg class="w-5 h-5 text-gray-400 me-1 dark:text-gray-300" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                  </svg>
                <% end %>
                <p class="ms-1 text-base font-bold text-black-500 dark:text-gray-600"><%= property.avg_final_rating.to_f.round(2) %></p>
                <p class="ms-1 text-sm font-medium text-gray-500 dark:text-gray-400">(<%= property.reviews_count %>)</p>
              </div>
              <div style="display: flex; flex-direction: column; align-items: flex-end; margin-top: -20px;">
                 <button class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800">
                    <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent"> <%= "#{humanized_money_with_symbol(property.price)}" %> / night
                    </span>
                </button>
              </div>
              <div>
                <p class="font-bold text-green-500"><i>*Bookings Available On</i><b><%= ": #{property.available_dates}" %></b></p>
              </div>
            </div>
            <div class="mt-3 text-gray-600 text-sm md:text-sm flex flex-wrap gap-2">
              <span class="bg-blue-100 text-blue-800 text-sm font-medium px-2.5 py-0.5 rounded-full">Free Wifi</span>
              <span class="bg-red-100 text-red-800 text-sm font-medium px-2.5 py-0.5 rounded-full">Express Check-In</span>
              <span class="bg-green-100 text-green-800 text-sm font-medium px-2.5 py-0.5 rounded-full">Breakfast</span>
              <span class="bg-orange-100 text-orange-800 text-sm font-medium px-2.5 py-0.5 rounded-full">Bike Rental</span>
              <span class="bg-indigo-100 text-indigo-800 text-sm font-medium px-2.5 py-0.5 rounded-full">Parking</span>
              <span class="bg-purple-100 text-purple-800 text-sm font-medium px-2.5 py-0.5 rounded-full">Free Pool Access</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayHotels | Holiday Rentals | Best Price Guarantee!</title>
    <%= favicon_link_tag 'hotels_favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if controller_name != 'registrations' && controller_name != 'sessions' %>
      <%= render 'layouts/templates/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/templates/_navbar.html.erb
<header class="bg-white shadow" data-controller="navbar">
  <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:divide-y lg:divide-gray-200 lg:px-8">
    <div class="relative flex h-24 justify-between">
      <div class="relative z-10 flex px-2 lg:px-0">
        <div class="flex flex-shrink-0 items-center">
          <%= link_to root_path do %>
            <%= show_svg('logo.svg') %>
          <% end %>
        </div>
      </div>
      <div class="relative z-0 flex flex-1 items-center justify-center px-2 sm:absolute sm:inset-0">
        <div class="w-full sm:max-w-xs">
          <label for="search" class="sr-only">Search</label>
          <div class="relative">
            <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
              </svg>
            </div>
            <input id="search" name="search" class="block w-full rounded-md border-0 bg-white py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="Search" type="search">
          </div>
        </div>
      </div>
      <div class="relative z-10 flex items-center lg:hidden">
        <!-- Mobile menu button -->
        <button data-navbar-target="mobileNavbarDrop" type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open menu</span>

          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>

          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:relative lg:z-10 lg:ml-4 lg:flex lg:items-center">
        <!-- Profile dropdown -->
        <div class="relative ml-4 flex-shrink-0">
          <div>
            <button data-navbar-target="openUserInfo" type="button" class="relative flex rounded-full bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>

          <div 
            data-transition-enter="transition ease-out duration-100"
            data-transition-enter-start="transform opacity-0 scale-100"
            data-transition-enter-end="transform opacity-60 scale-100"
            data-transition-leave="transition ease-in duration-75"
            data-transition-leave-start="transform opacity-100 scale-220"
            data-transition-leave-end="transform opacity-0 scale-105"
            data-navbar-target = "userDropdown" class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <% if user_signed_in? %>
              <%= link_to "Favorites", "", class:"block px-4 py-2 text-sm text-gray-700", role:"menuitem", tabindex:"-1", id:"user-menu-item-3" %>
              <%= link_to "Logout", destroy_user_session_path, data: {"turbo_method": :delete }, class:"block px-4 py-2 text-sm text-gray-700", role:"menuitem", tabindex:"-1", id:"user-menu-item-2" %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, data: {"turbo_method": :get }, class:"block px-4 py-2 text-sm text-gray-700", role:"menuitem", tabindex:"-1", id:"user-menu-item-0" %>
              <%= link_to "Login", new_user_session_path, data: {"turbo_method": :get }, class:"login block px-4 py-2 text-sm text-gray-700", role:"menuitem", tabindex:"-1", id:"user-menu-item-1" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <nav class="lg:hidden" aria-label="Global" id="mobile-menu">
    <div data-navbar-target="userMobileDropdown" class="hidden border-t border-gray-200 pb-3 pt-4">
      <% if user_signed_in? %>
        <div class="flex items-center px-4">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="ml-3">
            <div class="text-base font-medium text-gray-800">Tom Cook</div>
            <div class="text-sm font-medium text-gray-500">tom@example.com</div>
          </div>
        </div>
      <% end %>
      <div class="mt-3 space-y-1 px-2">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, data: {"turbo_method": :delete }, class:"block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, data: {"turbo_method": :get }, class:"block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900" %>
          <%= link_to "Login", new_user_session_path, data: {"turbo_method": :get }, class:"block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/properties/_amenites_with_facilities.html.erb
<div class="container mx-auto px4 py-8">
  <div class="w-full px-4">
    <div class="max-w-10-xl mx-auto p-4 bg-white shadow-lg rounded-lg">
      <h2 class="text-2xl font-bold mb-4">Amenities and Facilities of <%= properties.name %></h2>
      
      <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
        <!-- Languages Spoken -->
        <div>
          <h3 class="font-bold mb-2">Languages spoken</h3>
          <div class="flex items-center space-x-2">
            <img src="https://flagcdn.com/w40/gb.png" alt="English" class="w-6 h-4">
            <span>English</span>
          </div>
          <div class="flex items-center space-x-2">
            <img src="https://flagcdn.com/w40/in.png" alt="Hindi" class="w-6 h-4">
            <span>Hindi</span>
          </div>
        </div>

        <!-- Internet Access -->
        <div>
          <h3 class="font-bold mb-2">Internet access</h3>
          <p>✅ Free Wi-Fi in all rooms!</p>
          <p>✅ Internet</p>
          <p>✅ Internet services</p>
        </div>

        <!-- Services and Conveniences -->
        <div>
          <h3 class="font-bold mb-2">Services and conveniences</h3>
          <p>✅ Daily housekeeping</p>
          <p class="text-gray-400 line-through">❌ Elevator</p>
          <p class="text-gray-400 line-through">❌ Smoking area</p>
        </div>

        <!-- Access -->
        <div>
          <h3 class="font-bold mb-2">Access</h3>
          <p>✅ Check-in/out [private]</p>
          <p>✅ Check-in [24-hour]</p>
          <p>✅ <a href="#" class="text-blue-500">Front desk [24-hour]</a></p>
          <p class="text-gray-400 line-through">❌ Pets allowed</p>
        </div>

        <!-- Getting Around -->
        <div>
          <h3 class="font-bold mb-2">Getting around</h3>
          <p>✅ Car park [on-site]</p>
        </div>
      </div>

    </div>
   </div> 
</div>  

app/views/properties/_reviews.html.erb
<% total_reviews_count = properties.reviews_count %>
<div class="container mx-auto px4 py-8">
  <div class="w-full px-4">
    <div class="max-w-10-xl mx-auto p-4 bg-white shadow-lg rounded-lg">

      <h1 class="text-2xl font-bold mb-4">Reviews of <%= properties.name %></h1>
      <div class="flex items-center mt-6">
        <div class="bg-blue-600 text-white text-3xl font-bold px-4 py-2 rounded"><%= properties.avg_final_rating.to_f.round(2) %></div>
        <div class="ml-6 w-full">
          <%= display_property_review_averages(properties.reviews) %>
        </div>
      </div>

      <div data-controller="reviews">
        <div class="mt-6 p-6 flex flex-col items-center">
          <span>Showing <%= total_reviews_count %> comments</span>
        </div>
        <% properties.reviews.each_with_index do |prop_reviews, index| %>
          <div class="border-b pb-4 mb-4 <%= 'hidden' if index >= 2 %>" data-reviews-target="review">
            <div class="flex">
              <div class="w-1/3">
                <p class="text-blue-600 font-bold"><%= final_rating_label(prop_reviews.final_rating) %></p>
                <p class="font-bold">Anonymous</p>
              </div>
              <div class="w-2/3">
                <div class="bg-gray-100 p-4 rounded-lg">
                  <p class="text-gray-700 text-sm mt-2">
                    <%= prop_reviews.content %>
                  </p>
                  <p class="text-gray-500 text-xs mt-2">Reviewed <%= prop_reviews.created_at.strftime("%B %d, %Y") %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <% if total_reviews_count > 2 %>
          <div class="text-center mt-4">
            <button data-action="click->reviews#toggle" class="bg-blue-500 text-white px-4 py-2 rounded">
              Show More
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>